fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user_login:
    path:    /
    defaults: { _controller: AppBundle:Security:login }

user_login_check:
    path:    /user/login/check
    defaults: { _controller: AppBundle:Security:check }

dashboard:
    path:    /dashboard
    defaults: {_controller: AppBundle:Default:index}

# ------- User Route -------
profil:
    path:    /profil/{iduser}
    defaults: {_controller: AppBundle:Default:profil}

new_user:
    path:    /user/new
    defaults: {_controller: AppBundle:Default:newUser}

show_user:
    path:    /user/list
    defaults: {_controller: AppBundle:Default:listUser}

# ------ Product Route -------
new_product:
    path:    /product/new
    defaults: {_controller: ProductBundle:Product:newProduct}

show_product:
    path:    /product/show
    defaults: {_controller: ProductBundle:Product:listProduct}

fiche_product:
    path:    /product/fiche/{idproduct}
    defaults: {_controller: ProductBundle:Product:ficheProduct}

# ------ Product Route -------
all_enchere:
    path:    /enchere/all
    defaults: {_controller: DealBundle:Enchere:allEnchere}

my_enchere:
    path:    /enchere/user
    defaults: {_controller: DealBundle:Enchere:myEnchere}

fiche_enchere:
    path:    /enchere/fiche/{idenchere}
    defaults: {_controller: DealBundle:Enchere:ficheEnchere}