<?php

namespace DealBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EncheresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EncheresRepository extends EntityRepository
{
}
